server:
  port: 9999
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pharmacy
    username: postgres
    password : iloveu
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

